# # Usa una imagen base de Node.js
# FROM node:16

# # Establece el directorio de trabajo en el contenedor
# WORKDIR /usr/src/app

# # Copia el package.json y package-lock.json al contenedor
# COPY package*.json ./

# # Instala las dependencias de la aplicación
# RUN npm install

# # Copia el resto de los archivos de tu proyecto al contenedor
# COPY . .

# # Expone el puerto 5000 para la aplicación
# EXPOSE 5000

# # Define el comando para ejecutar la aplicación con nodemon
# CMD ["npx", "nodemon", "index.js"]
